name: Security Test
on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Hawk 
        uses: actions/setup-go@v5
        with: 
          go-version: "1.24"

      - name: Build Hawk 
        run: go build -o hawk ./cmd/hawk

      
